// my-react-app/src/components/Nav.jsx
import React, { useState } from 'react';
import logo from '../logo.svg';

export default function Nav() {
    let [isOpen, setIsOpen] = useState(false);

    return (  
    <nav className="navbar" role="navigation" aria-label="main navigation">
    <div className="navbar-brand">
        <a className="navbar-item" href="https://bulma.io">
            <img src={logo} className="App-logo" alt="logo" height="28" />
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28" />
        </a>

        <a className={ `${isOpen ? 'is-active' : ''} navbar-burger burger` } onClick={()=> setIsOpen(!isOpen)} role="button" aria-label="menu" aria-expanded="false" >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
        
    <div className={ `navbar-menu ${isOpen ? 'is-active' : '' }`} >
        <div className="navbar-start">


        <router-link to="/" className="navbar-item" active-className="is-current" exact>Home</router-link>
        <router-link to="/about" className="navbar-item" active-className="is-current">About</router-link>
        <router-link to="/game" className="navbar-item" active-className="is-current">Game</router-link>


        <div className="navbar-item has-dropdown is-hoverable">
            <a className="navbar-link">
            More
            </a>

            <div className="navbar-dropdown">
            <a className="navbar-item">
                About
            </a>
            <a className="navbar-item">
                Jobs
            </a>
            <a className="navbar-item">
                Contact
            </a>
            <hr className="navbar-divider" />
            <a className="navbar-item">
                Report an issue
            </a>
            </div>
        </div>
        </div>

        <div className="navbar-end">
        <div className="navbar-item">
            <div className="buttons">
            <a className="button is-primary">
                <strong>Sign up</strong>
            </a>
            <a className="button is-light" href="/login">
                Log in
            </a>
            </div>
        </div>
        </div>
    </div>
    </nav>
)
    }

// client/src/components/Nav.vue
<template>
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a :class="{ 'is-active':isOpen }" @click="isOpen = !isOpen" role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div :class="{ 'is-active':isOpen }" class="navbar-menu">
    <div class="navbar-start">


      <router-link to="/" class="navbar-item">Home</router-link>
      <router-link to="/about" class="navbar-item">About</router-link>


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>
</template>

<script>
export default {
  data: ()=>({
    isOpen: false
  })
}
</script>

<style>

</style>
